### ISSUE TITLE
Deprecate Function Error in Admin Area

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#10]
On first access of admin section following error displayed

( ! ) Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in C:\wamp64\www\testsite\class\mail\phpmailer\PHPMailerAutoload.php on line 45

Error does not appear on subsequent access.  

Error reappears after clearing browser history and restarting the browser

PHP Version: 7.2.18
mySQL Version: 5.7.26
Server API: apache2handler
OS: WINNT (Windows 10)

**Comment by ggoffy** [comment]
please update your XOOPS core

**Comment by djsherren** [comment]
Updating the Xoops core did the trick.  No longer seeing the error
