### ISSUE TITLE
Photo Links Not Working on "Popular" and "Top Rated" pages

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#15]
On the “Popular” and “Top Rated” pages, the hyper link to the listed photos is not properly constructed, As a result the link is not displayed.

Current link: 

<ahref='photo.php?cid=1&amp;lid=1'>imgl5c542c52262660.40013729</a>

Suggested link:

<a href='photo.php?cid=1&amp;lid=1'>imgl5c542c52262660.40013729</a>

A correction needed in /templates/myalbum_topten.tpl at line 37. The hyper link spans line 37 and 38 and should all be on one line.

**Comment by djsherren** [comment]
Suggested link should have read <a href etc.

**Comment by ggoffy** [comment]
fixed, thank you
