### ISSUE TITLE
User IP address not Properly Recorded in DB when User Rates a Photo

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#17]
User IP address is not properly recorded in the database when a rating an image.  The address is truncated to an integer. For example an address such as 73.123.45.67 is recorded as 73.

Suggest changing class/Votedata.php line 28

from:  $this->initVar('ratinghostname', \XOBJ_DTYPE_INT, null, false);

to:    $this->initVar('ratinghostname', \XOBJ_DTYPE_TXTBOX, null, false);

**Comment by ggoffy** [comment]
fixed, thank you
