### ISSUE TITLE
Cannot Delete a Photo

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#6]
Permissions – Super Delete is selected.

In album view – no error message, page reloads, photo is still present.

In photo view – no error message, album view reloads, photo is still present.

In Admin – MyAlbum - Photo Manager selecting photos and then selecting delete results in notification “Deleting photos” – no error message, photo not removed.

In Admin – MyAlbum - Photo Manager  - selecting the edit button for a photo results in the Photo Edit and Reupload page in the front end to be displayed.  Deleting the photo from this page causes the following error to appear.
Fatal error: Cannot redeclare themecenterposts() (previously declared in C:\wamp64\www\testsite\include\old_theme_functions.php:45) in C:\wamp64\www\testsite\include\cp_functions.php on line 6 

PHP Version: 7.2.18
mySQL Version: 5.7.26
Server API: apache2handler
OS: WINNT (Windows 10)

**Comment by ggoffy** [comment]
deleting should work now
can you please test again

**Comment by djsherren** [comment]
Deleting photos now works.  Thank you for the fix.
