### ISSUE TITLE
Cannot Rebuild Thumbnails

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#7]
Settings
Force recreating of thumbnails even if a thumbnail exists – yes
Remove records that don’t link to a main photo – yes
Resize bigger photos than the pixels specified in current preferences - yes

Dates on thumbnails do not change

Deleting all thumbnails in uploads/myalbum/thumbnails and then starting "Recreating Thumbnails" Does not result in any thumbnails being created.

Thumbnails are created when a photo is uploaded

PHP Version: 7.2.18
mySQL Version: 5.7.26
Server API: apache2handler
OS: WINNT (Windows 10)

**Comment by ggoffy** [comment]
creation of thumbs should work now
can you please test again

**Comment by djsherren** [comment]
Can now update and create new thumbs. Thank you for the fix.
