### ISSUE TITLE
No error message when trying to enter a photo larger than the size limits in the preferences.

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#8]
No photo is entered.  No error message is displayed.  Upload Photo page reloads.

A photo within size limits is properly uploaded. "We recieved your photo. Thanks!" message displayed.  Thumbnail is generated.

PHP Version: 7.2.18
mySQL Version: 5.7.26
Server API: apache2handler
OS: WINNT (Windows 10)

**Comment by ggoffy** [comment]
should work now
can you please test again

**Comment by djsherren** [comment]
Error message now appears when attempting to upload a large photo. Thank you for the fix.
