### ISSUE TITLE
Thumbnail links for blocks are incorrect

### ISSUE THREAD

**Issue by djsherren** [XoopsModules25x/myalbum#9]
For the Random Photo Block, the thumbnail link is: http://localhost/testsite/uploads/photos//11.jpg

For the Top Images with Thumbs Block the thumbnail link is: http://localhost/1.jpg

PHP Version: 7.2.18
mySQL Version: 5.7.26
Server API: apache2handler
OS: WINNT (Windows 10)

**Comment by djsherren** [comment]
Also applies to Recent Photos with thumbs where the thumbnail link is: http://localhost/1.jpg

**Comment by ggoffy** [comment]
should work now
can you please test again

**Comment by djsherren** [comment]
Thumbnails are now properly displayed on the blocks. Thank you for the fix.

**Comment by djsherren** [comment]
:)
